# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-Yandex
version:      0.04
version_from: lib/WWW/Search/Yandex.pm
installdirs:  site
requires:
    HTML::TreeBuilder:             3.13
    URI:                           1.31
    URI::Escape:                   3.26
    WWW::Search:                   2.528
    WWW::SearchResult:             2.061

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
